[package]
name = "rust_for_multimedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
convolve2d = { version = "0.1.0", features = ["full"] }
rayon = "1.5.1"
itertools = "0.10.3"